### ISSUE TITLE
dunno

### ISSUE THREAD

**Issue by Mounirbendaia** [BlackDracula/Uni-java-code#1]
package sample;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.layout.GridPane;
import javafx.scene.text.Text;
import javafx.stage.Stage;

import java.util.LinkedHashSet;
import java.util.Scanner;

public class Main extends Application {
    GridPane gridPane = new GridPane();
    static Text Value_M = new Text();
    static String Value_M_S="";
    static Text Com_M= new Text();
    static String Com_M_M="";
    static Text Value_Q = new Text();
    static String Value_Q_M="";
    static Text A = new Text();
    static String A_String="";
    static Text Q = new Text();
    static String Q_String="";
    static Text Q_1 = new Text();
    static String Q1_String="";
    static Text M = new Text();
    static String M_String="";
    static Text OP = new Text();
    static String ST_OP ="";
    public void start(Stage primaryStage) throws Exception {
        // TODO Auto-generated method stub

        Scanner input = new Scanner(System.in);

        System.out.println("Booth Algorithm Test\n");

        System.out.println("Enter two integer numbers\n");
        int multipicand = input.nextInt();

        int multiplier = input.nextInt();

        int m[]= binary (multipicand) ;

        int twocommplementOfM[]=binary (-multipicand) ;

        int q[]= binary (multiplier) ;

        System.out.print("M :");

        for (int s : m) {
            Value_M_S += s;
            System.out.print(" " + s);
        }
        Value_M.setText(Value_M_S);
        Value_M_S += "\n";

        System.out.print("\n\ncommplementOfM :");

        for (int s : twocommplementOfM) {
            System.out.print(" " + s);
            Com_M_M += s;
        }
        Com_M.setText(Com_M_M);
        Com_M_M +="\n";
        System.out.print("\n\nQ :");

        for (int s : q) {
            System.out.print(" " + s);
            Value_Q_M += s;
        }
        Value_Q.setText(Value_Q_M);
        Value_Q_M += "\n";
        Value_Q_M += "\n";
        Value_Q_M += "\n";
        System.out.println(" \n\n" );

        int a[]={0,0,0,0};

        int Q1=0;

        int count=4;

        System.out.println("A \t Q \tQ-1\t M \toperation");

        display(a,q,Q1,m);

        System.out.print("Initial\n");
        OP.setText(ST_OP);
        ST_OP += "Initial\n";

        for(int i=count;i>0;i--)
        {

            if(q[3] == 0 && Q1 == 1)  //if  Q0 and Q-1 = 01
            {
                // we add A and M
                a=  adding (a,m);

                display(a,q,Q1,m);

                System.out.print("A = A+M\n");
                ST_OP += "A=A+M";
                OP.setText(ST_OP);
                ST_OP+="\n";
            }

            if( q[3] == 3 && Q1 == 0  )  // if  00

                ;    // we skip and go straight  to shifting

            if (  q[3] == 1 &&  Q1==1  ) // if  11

                ; // we skip and go straight  to shifting

            if( q[3] == 1 &&  Q1 ==  0  )// if  10 we subtract A and M or we add A and the complement
            {

                // we add A and the complement of M

                a = adding (a,twocommplementOfM);

                display(a,q,Q1,m);

                System.out.print("A = A-M\n");
                ST_OP += "A = A-M";
                OP.setText(ST_OP);
                ST_OP+="\n";
            }

            Q1=q[3];  // start shift this first because q[3] will change in the method 'shift'

            rightShift(a,q);

            display(a,q,Q1,m);

            System.out.print("shift\n");
            ST_OP += "Shift";
            OP.setText(ST_OP);
            ST_OP+="\n";
        }

        GridPane gridPane = new GridPane();
        gridPane.setAlignment(Pos.TOP_LEFT);
        gridPane.setHgap(5);
        gridPane.setVgap(5);
        gridPane.add(Value_M,0,0);
        gridPane.add(Com_M,0,1);
        gridPane.add(Value_Q,0,2);
        gridPane.add(A,0,6);
        gridPane.add(Q,2,6);
        gridPane.add(Q_1,4,6);
        gridPane.add(M,6,6);
        gridPane.add(OP,9,6);
        primaryStage.setTitle("Booth agorithm");
        Scene second_scene = new Scene(gridPane, 300 , 300); // second scene to show the calculations
        primaryStage.setScene(second_scene);
        primaryStage.show();

    }

    //----------------------------------------

    public static void display(int a[],int q[],int Q1,int m[])
    {

        for(int i=0;i<4;i++)
        {

            System.out.print(a[i]);
            A_String += a[i];
        }
        A.setText(A_String);
        A_String += "\n";
        System.out.print("\t");

        for(int i=0;i<4;i++)
        {

            System.out.print(q[i]);
            Q_String += q[i];
        }
        Q.setText(Q_String);
        Q_String +="\n";

        System.out.print("\t");
        System.out.print(Q1);
        Q1_String += Q1;
        Q_1.setText(Q1_String);
        Q1_String +="\n";
        System.out.print("\t");

        for(int i=0;i<4;i++)
        {

            System.out.print(m[i]);
            M_String += m[i];
        }
        M.setText(M_String);
        M_String += "\n";
        System.out.print("\t");

    }

    //--------------------------------
    /*
     * a method to transfer decimal to binary, it receive an int
     * it will also find the complement (to do that,you have to pass negative number )
     * it will return an array type int
     * */

    public static int[] binary(int n)
    {
        int[] binArr = new int[4];
        int indexStartFromThree = 3;
        int num = n;

        // for negative numbers 2 complment

        if (n < 0)
            /// when you add 16 , it will give you the complement
            num = 16 + n;
        /// from -1 to -15

        while (num != 0)
        {
            binArr[indexStartFromThree--] = num % 2;

            /* if num = 10
             *
             * bin[3] = 10 %2 = 0
             * bin[2] =5 %2 = 1
             * bin[1] =2 %2 = 0
             * bin[0] =1 %2 = 1
             *
             * */

            num /= 2;
        }

        return binArr;
    }

    //-------------------------------------------

    public static int[] adding (int[] A, int[] S)
    {
        int carry = 0;

        // int sum[]=new int [4];

        // we start from the last index because in addition it start from there

        for (int i = 3; i >= 0; i--)
        {
            int addition = A[i] + S[i] + carry;
            A[i] = addition % 2;
            carry = addition / 2 ;
        }

        return A ;

        //example
        /* loop1
         * A[3]=1 , B[3]= 0 , carry = 0
         *
         * addition =1 + 0 +0 =1
         *
         * A[3] = 1 % 2 = 1
         *
         * carry = 1 /2 = 0
         * -------------------------
         * loop2
         * A[2]=1 , B[2]= 1 , carry = 0
         *
         * addition =1 + 1 +0 =2
         *
         * A[2] = 2 % 2 = 0
         *
         * carry = 2 /2 = 1
         *
         *
         *
         * -------------------------
         * loop3
         * A[1]=1 , B[1]= 1 , carry = 1
         *
         * addition =1 + 1 +1 =3
         *
         * A[1] = 3 % 2 = 1
         *
         * carry = 3 /2 = 1
         *
         *
         *
         * -------------------------
         * loop4
         *
         * A[0]=0 , B[0]= 1 , carry = 1
         *
         * addition =0 + 1 +1 =2
         *
         * A[0] = 2 % 2 = 0
         *
         * carry = 2 /2 = 1  (will not be use )
         *
         * */

    }

    public static void rightShift (int a[],int q[])

    {

        int lastElementIn_A = a[3]; // the last element in A will shift to q[0]

        for(int i=2;i>=0;i--)
        {

            a[i+1]=a[i];
            /*
             * a3 =a2
             *
             * a2=a1
             *
             * a1=a0
             *
             * a0= a0
             *
             * */
            q[i+1]=q[i];

            // q0 = q0  is wrong but change it outside the loop
        }
        q[0] = lastElementIn_A ;

    }
    public static void main(String[] args) {
        launch(args);
    }
}

**Comment by abuyusif01** [comment]
Yoo modafuka

**Comment by Mounirbendaia** [comment]
Yew what the fuck🤣🤣🤣🤣
